### PR TITLE
Store active Fiber instance separately from current fiber context

### PR DESCRIPTION
**Pull request by trowski**
@kooldev Any suggestions for an easy way to test this in `zend_test`?

### CODE REVIEW

**Comment by kooldev** [comment]
Maybe add a class `TestFiber` to `zend_test` and implement just `TestFiber::start()`. You could basically copy the code from `Fiber` and leave out suspend, error handling, return value, etc. I am not really sure where you are going with that...

```php
$fiber = new Fiber(function () {
    $test = new TestFiber(function () {
        return Fiber::suspend(123);
    });
    var_dump($test->start());
    return 1;
});
$fiber->resume(2 * $fiber->start());
```
What would you expect this to do? Do you expect this to print `int(246)`?

**Comment by trowski** [comment]
> Do you expect this to print `int(246)`?

Yes, precisely.

**Comment by trowski** [comment]
We should be able to allow nesting of multiple fiber implementations so long as we keep track of where `Fiber::suspend()` is suppose to go, which this PR does. This way, a future built-in scheduler or a Swoole fiber could coexist with `Fiber`.

**Comment by kooldev** [comment]
OK, what about doing it in opposite order (assuming `TestFiber::suspend()` was implemented):

```php
$test = new TestFiber(function () {
    $fiber = new Fiber(function () {
        TestFiber::suspend();
    });
    $fiber->start();
});
$test->start();
```
I am assuming this would throw an error from `TestFiber::suspend()` because `EG(current_fiber_context)` refers to a `zend_fiber`... this behavior would be somewhat inconsistent.

What is the purpose of handling `Fiber` in a different way?

**Comment by trowski** [comment]
The implementation of `TestFiber` would need to keep track of which fiber context is related to `TestFiber::suspend()` in the same way. If `zend_test` implements `TestFiber::suspend()`, it would need a module global that mirrors `EG(active_fiber)` and the `TestFiber` object implementation would need a `zend_fiber_context *caller` pointer to record the context that called `TestFiber::start()`.

Hopefully that makes sense. With symmetric fibers internally, this should work well.

The purpose is so that an extension which creates custom fibers or a future async/await implementation that creates internal fibers does not conflict with the expected behavior of `Fiber` and so `Fiber::suspend()` does not interfere with custom scheduling.

**Comment by trowski** [comment]
Consider something like this in future, which should work:

```php
$fiber = new Fiber(function () {
    $future = async (function () {
        return Fiber::suspend(1);
    })();
    
    var_dump(await $future); // int(2)
});

var_dump($fiber->start()); // int(1)
var_dump($fiber->resume(2)); // NULL
```

`async` would create a fiber internally, but `Fiber::suspend()` does not interact with it, it skips back to the context that started the fiber.

**Comment by kooldev** [comment]
Would you really need to maintain `EG(current_fiber)` for that? If we move `caller` to `zend_fiber_context` you have a nice linked list that you can follow until `kind = X` and be done. This would also work for other fiber types.

**Comment by trowski** [comment]
Maintaining `caller` has become complicated because fibers are no longer strictly a push/pop stack. Another implementation could jump back several contexts. How do you modify the linked list when that occurs?

**Comment by kooldev** [comment]
Don't you have the same problem in `zend_fiber_switch_to()` where you backup the fiber and restore it after the context switch? This is also a stack (the call stack in this case). Imagine you resume a `Fiber` and a symmetric context switch occurs. After that you find yourself in code that is wrapped within a different `Fiber` but `EG(active_fiber)` is still pointing to the first one...

Anyways I need to go to bed now. I will think about it tomorrow.

**Comment by trowski** [comment]
> After that you find yourself in code that is wrapped within a different Fiber but EG(active_fiber) is still pointing to the first one...

Perhaps `EG(active_fiber)` needs to be backed-up/restored with the other EG globals then.

> Anyways I need to go to bed now. I will think about it tomorrow.

Have good night. I think I'll stop looking at this for a little while myself as well.

**Comment by trowski** [comment]
@kooldev Pushed what I was working on for now, feel free to change & push as you like. I'm close to it working I think, but too tired to focus anymore. Off to bed.

**Comment by trowski** [comment]
@kooldev Got it working! This now does what I intended – `Fiber` can suspend in and out of a custom fiber implementation and vice-versa. This should allow interop between `Fiber`, Swoole, and any future fiber-based async/await implementation. 🥳

I need to add a few more tests based on `_ZendTestFiber`, but it's late now so I'm off to bed, will work on this more tomorrow morning.

**Pull request closed without merging**
